### PR TITLE
Fixes #97 - Add a decorator to select test based on minimum/maximum

### LINKED ISSUE #97: Add a decorator to select test based on minimum/maximum version
Lets have a decorator for selecting test based on minimum or maximum version.

Ex: 
1. test will run for version 6.6 and above then, start_in('6.6') /
2. test will run for version less than 6.5, ends_in('6.5')

### PR DESCRIPTION
**Pull request by jameerpathan111**
Fixes #97

### CODE REVIEW

**Comment by ntkathole** [comment]
@jameerpathan111 can we use it for capsule as well?

**Comment by jameerpathan111** [comment]
Also fixes #104

**Comment by ntkathole** [comment]
Have you tested if we can assign both decorators. ex: if test is valid for only 6.4 and 6.5
```
@starts_in('6.4')
@ends_in('6.5')
```

**Comment by jameerpathan111** [comment]
> Have you tested if we can assign both decorators. ex: if test is valid for only 6.4 and 6.5
> 
> ```
> @starts_in('6.4')
> @ends_in('6.5')
> ```

No I haven't. Will test this.

**Comment by jameerpathan111** [comment]
> No I haven't. Will test this.
@ntkathole I have tried this and we can use both decorators.

**Pull request merged**
