### PR TITLE
Automate hotfix check #44

### PR DESCRIPTION
**Pull request by jameerpathan111**
Fixes issue #44 
Test Results:

```
$ pytest --ansible-host-pattern satellite --ansible-user=root  --ansible-inventory testfm/inventory tests/test_health.py -k test_positive_check_hotfix_installed_with_file_changed -svvv
========================================================================= test session starts ==========================================================================
collected 12 items / 11 deselected                                                                                                                                     

tests/test_health.py::test_positive_check_hotfix_installed_with_file_changed 2019-01-18 13:33:45,217 - testfm.log - INFO - Running ForemanMaintain::Scenario::FilteredScenario
================================================================================
Check to verify if any hotfix installed on system: 
- Checking for presence of hotfix(es). It may take some time to verify.         
                                                                      [WARNING]



Found 1 file(s) modified on this system.
/opt/theforeman/tfm/root/usr/share/gems/gems/fog-vsphere-2.4.0/lib/fog/vsphere/requests/compute/list_clusters.rb

*** WARNING: Before update make sure the updated packages contain the listed modifications
*** otherwise these fixes will be lost. 
*** It is also recommended to backup the modified files prior update.
--------------------------------------------------------------------------------
Scenario [ForemanMaintain::Scenario::FilteredScenario] failed.

The following steps ended up in warning state:

  [check-hotfix-installed]

The steps in warning state itself might not mean there is an error,
but it should be reviews to ensure the behavior is expected
PASSED

============================================================== 1 passed, 11 deselected in 227.42 seconds ===============================================================

```

```
$ pytest --ansible-host-pattern satellite --ansible-user=root  --ansible-inventory testfm/inventory tests/test_health.py -k test_positive_check_hotfix_installed -svvv
========================================================================= test session starts ==========================================================================
collected 12 items / 11 deselected                                                                                                                                     

tests/test_health.py::test_positive_check_hotfix_installed 2019-01-18 14:22:13,765 - testfm.log - INFO - Running ForemanMaintain::Scenario::FilteredScenario
================================================================================
Check to verify if any hotfix installed on system: 
\ Checking for presence of hotfix(es). It may take some time to verify.         
                                                                      [OK]
--------------------------------------------------------------------------------
PASSED

============================================================== 1 passed, 11 deselected in 191.70 seconds ===============================================================
```

### CODE REVIEW

**Comment by sghai** [comment]
Good addition to check installed hot-fix. Would like to sync-up and know more about this change.

**Comment by jameerpathan111** [comment]
> Good addition to check installed hot-fix. Would like to sync-up and know more about this change.

sure.

**Comment by dollyparton** [comment]
[test]

**Comment by ntkathole** [comment]
ok to test : tests/test_health.py

**Comment by ntkathole** [comment]
ok to test : tests/test_health.py

**Comment by ntkathole** [comment]
ok to test : tests/test_health.py

**Comment by ntkathole** [comment]
ok to test : tests/test_health.py

**Comment by ntkathole** [comment]
ok to test : tests/test_health.py

**Comment by ntkathole** [comment]
ok to test : tests/test_health.py

**Comment by ntkathole** [comment]
ok to test : tests/test_health.py

**Comment by ntkathole** [comment]
ok to test : tests/test_health.py

**Comment by ntkathole** [comment]
ok to test : tests/test_health.py

**Comment by ntkathole** [comment]
ok to test : tests/test_health.py

**Comment by ntkathole** [comment]
ok to test : tests/test_health.py -k test_positive_foreman_maintain_health_list

**Comment by ntkathole** [comment]
ok to test : tests/test_health.py -k test_positive_foreman_maintain_health_list

**Comment by ntkathole** [comment]
ok to test : tests/test_health.py -k test_positive_foreman_maintain_health_list

**Comment by ntkathole** [comment]
ok to test

**Comment by ntkathole** [comment]
test

**Comment by ntkathole** [comment]
ok to test

**Comment by ntkathole** [comment]
ok to test

**Comment by ntkathole** [comment]
ok to test

**Comment by ntkathole** [comment]
ok to test

**Comment by ntkathole** [comment]
ok to test

**Comment by ntkathole** [comment]
ok to test

**Comment by ntkathole** [comment]
ok to test : tests/test_health.py -k test_positive_foreman_maintain_health_list

**Comment by ntkathole** [comment]
ok to test

**Comment by ntkathole** [comment]
ok to test

**Comment by ntkathole** [comment]
ok to test

**Comment by ntkathole** [comment]
testing

**Comment by ntkathole** [comment]
ok to test : tests/test_health.py -k test_positive_foreman_maintain_health_list

**Comment by jameerpathan111** [comment]
Test Results:
```
$ pytest --ansible-host-pattern satellite --ansible-user=root  --ansible-inventory testfm/inventory tests/test_health.py -k test_positive_check_hotfix_installed -svvv
=================================================================================== test session starts ===================================================================================
collected 15 items / 13 deselected                                                                                                                                                        

tests/test_health.py::test_positive_check_hotfix_installed 2019-05-31 09:59:57,685 - testfm.log - INFO - Running ForemanMaintain::Scenario::FilteredScenario
================================================================================
Check to verify if any hotfix installed on system: 
\ Checking for presence of hotfix(es). It may take some time to verify.         
                                                                      [WARNING]

HOTFIX rpm(s) applied on this system:
hotfix-package-1.0.0-1.HOTFIX.noarch

Found 1 file(s) modified on this system.
/opt/theforeman/tfm/root/usr/share/gems/gems/fog-vsphere-3.0.0/lib/fog/vsphere/requests/compute/list_clusters.rb

*** WARNING: Before update make sure the updated packages contain the listed modifications
*** otherwise these fixes will be lost. 
*** It is also recommended to backup the modified files prior update.
--------------------------------------------------------------------------------
Scenario [ForemanMaintain::Scenario::FilteredScenario] failed.

The following steps ended up in warning state:

  [check-hotfix-installed]

The steps in warning state itself might not mean there is an error,
but it should be reviews to ensure the behavior is expected
PASSED
tests/test_health.py::test_positive_check_hotfix_installed_without_hotfix 2019-05-31 10:03:18,261 - testfm.log - INFO - Running ForemanMaintain::Scenario::FilteredScenario
================================================================================
Check to verify if any hotfix installed on system: 
\ Checking for presence of hotfix(es). It may take some time to verify.         
                                                                      [OK]
--------------------------------------------------------------------------------
PASSED

======================================================================== 2 passed, 13 deselected in 477.53 seconds ========================================================================
```

**Comment by ntkathole** [comment]
Fell free to merge when https://github.com/SatelliteQE/robottelo-ci/pull/1525 and gitlab PR merged

**Pull request merged**
