### PR TITLE
Fixes #196 - Add capsule repository setup test and fix satellite one (qe-test-coverage)

### LINKED ISSUE #196: Add test for capsule repositories setup and fix existing repolist for satellite.
Refs: https://bugzilla.redhat.com/show_bug.cgi?id=1869731

### PR DESCRIPTION
**Pull request by jameerpathan111**
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1869731

### CODE REVIEW

**Comment by jameerpathan111** [comment]
https://github.com/SatelliteQE/robottelo-ci/pull/1843 also needs to be merged for this to work.

**Comment by jameerpathan111** [comment]
Will add test result soon.

**Comment by jameerpathan111** [comment]
@lvrtelov @vsedmik need your review.

**Comment by jameerpathan111** [comment]
Test result:

```
$ pytest -sv --ansible-host-pattern server --ansible-user root --ansible-inventory testfm/inventory tests/test_advanced.py -k test_positive_capsule_repositories_setup 
============================= test session starts ==============================
collecting ... 1
collected 14 items / 13 deselected

tests/test_advanced.py::test_positive_capsule_repositories_setup 2020-10-13 12:58:29,747 - testfm.log - INFO - Running ForemanMaintain::Scenario
================================================================================
Setup repositories: 
/ Configuring repositories for 6.8                                    [OK]      
--------------------------------------------------------------------------------
2020-10-13 13:00:12,995 - testfm.log - INFO - Loaded plugins: product-id, search-disabled-repos, subscription-manager
repo id                                           repo name               status
beaker-Server                                     beaker-Server            5,231
beaker-Server-HighAvailability                    beaker-Server-HighAvail     52
beaker-Server-NFV                                 beaker-Server-NFV           21
beaker-Server-NFV-debuginfo                       beaker-Server-NFV-debug      9
beaker-Server-RT                                  beaker-Server-RT            15
beaker-Server-RT-debuginfo                        beaker-Server-RT-debugi      6
beaker-Server-ResilientStorage                    beaker-Server-Resilient     57
beaker-Server-SAP                                 beaker-Server-SAP           15
beaker-Server-SAP-debuginfo                       beaker-Server-SAP-debug      8
beaker-Server-SAPHANA                             beaker-Server-SAPHANA        8
beaker-Server-SAPHANA-debuginfo                   beaker-Server-SAPHANA-d      5
beaker-Server-debuginfo                           beaker-Server-debuginfo  2,232
beaker-Server-optional                            beaker-Server-optional   4,685
beaker-Server-optional-debuginfo                  beaker-Server-optional-    243
beaker-harness                                    beaker-harness             850
beaker-tasks                                      beaker-tasks            33,025
rhel-7-server-ansible-2.9-rpms/x86_64             Red Hat Ansible Engine      25
rhel-7-server-rpms/7Server/x86_64                 Red Hat Enterprise Linu 30,607
rhel-7-server-satellite-capsule-6.8-rpms/x86_64   Red Hat Satellite Capsu      0
rhel-7-server-satellite-maintenance-6-rpms/x86_64 Red Hat Satellite Maint     40
rhel-7-server-satellite-tools-6.8-rpms/x86_64     Red Hat Satellite Tools      0
rhel-server-rhscl-7-rpms/7Server/x86_64           Red Hat Software Collec 12,776
repolist: 89,910
2020-10-13 13:04:55,648 - testfm.log - INFO - Running ForemanMaintain::Scenario
================================================================================
Setup repositories: 
/ Configuring repositories for 6.8                                    [OK]      
--------------------------------------------------------------------------------
PASSED1


================== 1 passed, 13 deselected in 1018.83 seconds ==================

```

**Review by vsedmik — APPROVED** [review]

**Comment by jameerpathan111** [comment]
@vsedmik thanks for noticing it, updated the pr.

**Review by lvrtelov — APPROVED** [review]
LGTM (y)

**Comment by jameerpathan111** [comment]
Thanks for reviewing, merging the pr.

**Pull request merged**
