### PR TITLE
Fixes #183 - Add test for validate_yum_config check

### LINKED ISSUE #183: Add test for validate_yum_config check and remove old test related to check_yum_exclude_list
Refs: https://github.com/theforeman/foreman_maintain/pull/366

### PR DESCRIPTION
**Pull request by jameerpathan111**
Fixes #183

### CODE REVIEW

**Comment by Gauravtalreja1** [comment]
@jameerpathan111  Thanks for this PR, tested your changes locally, LGTM 👍

**Test Results:**
```
(.testfm) [gtalreja@gtalreja testfm]$ pytest --ansible-host-pattern server --ansible-user=root --ansible-inventory testfm/inventory -sqvv tests/test_health.py::test_positive_check_validate_yum_config
========================================================== test session starts ==========================================================
platform linux -- Python 3.8.6, pytest-3.6.1, py-1.9.0, pluggy-0.6.0 -- /home/gtalreja/sat_workspace/testfm/.testfm/bin/python3
cachedir: .pytest_cache
ansible: 2.6.19
rootdir: /home/gtalreja/sat_workspace/testfm, inifile:
plugins: ansible-2.2.2
collected 1 item

tests/test_health.py::test_positive_check_validate_yum_config 2021-01-04 12:35:01,795 - testfm.log - INFO - Running ForemanMaintain::Scenario::FilteredScenario
================================================================================
Check to validate yum configuration before upgrade:                   [FAIL]
exclude is set in /etc/yum.conf as below:
exclude='cat* bear*'
Unset this configuration as it is risky while yum update or upgrade!
--------------------------------------------------------------------------------
Scenario [ForemanMaintain::Scenario::FilteredScenario] failed.

The following steps ended up in failing state:

  [validate-yum-config]

Resolve the failed steps and rerun
the command. In case the failures are false positives,
use --whitelist="validate-yum-config"
2021-01-04 12:35:19,047 - testfm.log - INFO - Running ForemanMaintain::Scenario::FilteredScenario
================================================================================
Check to validate yum configuration before upgrade:                   [FAIL]
exclude,clean_requirements_on_remove are set in /etc/yum.conf as below:
exclude='cat* bear*'
clean_requirements_on_remove=1
Unset this configuration as it is risky while yum update or upgrade!
--------------------------------------------------------------------------------
Scenario [ForemanMaintain::Scenario::FilteredScenario] failed.

The following steps ended up in failing state:

  [validate-yum-config]

Resolve the failed steps and rerun
the command. In case the failures are false positives,
use --whitelist="validate-yum-config"
2021-01-04 12:35:36,615 - testfm.log - INFO - Running ForemanMaintain::Scenario::FilteredScenario
================================================================================
Check to validate yum configuration before upgrade:                   [OK]
--------------------------------------------------------------------------------
PASSED

======================================================= 1 passed in 57.68 seconds =======================================================
```

**Comment by vsedmik** [comment]
The code looks good, I was only concerned about changing the test name and keeping it's id (how is it paired in Polarion). Shall we change the id as well @jameerpathan111?

**Comment by jameerpathan111** [comment]
> The code looks good, I was only concerned about changing the test name and keeping it's id (how is it paired in Polarion). Shall we change the id as well @jameerpathan111?

@vsedmik good catch, the thing with testfm tests is that they are not in Polarion(future enhancement, will see if I can add them). So for now it's ok if we change test name or id.

**Review by vsedmik — APPROVED** [review]
:+1:

**Review by lvrtelov — APPROVED** [review]
LGTM

**Pull request merged**
